### ISSUE TITLE
`?.` operator not supported in VSC Remote.

### ISSUE THREAD

**Issue by rioj7** [ArturoDent/jump-and-select#3]
You use the `?.` operator. This is not supported in VSC Remote.

https://github.com/microsoft/vscode-remote-release/issues/4692

**Comment by rioj7** [comment]
They have updated Node for remote to v8.6 in VSC 1.56, that supports `??` so maybe also `?.`

**Comment by ArturoDent** [comment]
Closing.  If `??` is supported, the earlier operator `?.` must be supported by now.  If I hear differently, I'll reopen.
