### ISSUE TITLE
jumping back acting weird?

### ISSUE THREAD

**Issue by martin-hyca** [ArturoDent/jump-and-select#8]
Hi! First of all, big big up for this project.
I just installed it and it works great when jumping forward. 
However, when jumping back, the cursors jump to far. Is there any possible explanation for that? And, most importantly, a way to fix it? 

Bottom left corner you can see the keystrokes but they are not really saying much about anything else than the modifier keys due to my custom layout... I am searching for } when jumping forward and for { when jumping back. 

https://github.com/user-attachments/assets/506967a4-d5f4-4faf-9548-c2f06c441634

**Comment by ArturoDent** [comment]
I am having trouble reproducing this (although I get an off by one error in `.json` files when jumping backward, but not in other files).   Are you seeing the issue in other languages?

**Comment by martin-hyca** [comment]
I tested python, js, css, html - the same in all of them. However, whatever code I have in a unsaved file without lanugage defined, it works! 
I also tried to disable some other extensions and comment out some custom settings I had done, not sure I tried everything for that matter but nothing helped. 
Anything else I can try?

**Comment by ArturoDent** [comment]
I just figured out the bug and why it was strange.  It had to do with the length of the first line of the document and starting from the end of it instead of the beginning.  When I debugged it initially I must have had an empty line at the top and so it worked as expected!

Please try v.0.5.2 and let me know.   Thanks.
